# Generated by Django 3.2.7 on 2021-10-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations',
            name='long',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
