# Generated by Django 3.2.7 on 2021-10-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211025_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pin',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
